controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    assets.animation`myAnim4`,
    150,
    false
    )
    mySprite.sayText("Dancing", 1000, false)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    assets.animation`myAnim3`,
    200,
    false
    )
    mySprite.sayText("Squats", 1000, false)
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    .........fffff..........
    .........fffff..........
    .........fffff..........
    .........fffff..........
    .........fffff..........
    ...........f............
    ...........f............
    ...........f............
    ..........fff...........
    .........f.f.f..........
    ........f..f..f.........
    .......f...f...f........
    ...........f............
    ...........f............
    ...........f............
    ..........f.f...........
    ..........f.f...........
    .........f...f..........
    .........f...f..........
    ........f.....f.........
    `, SpriteKind.Player)
scene.setBackgroundColor(1)
